plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: Vilewing's homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
